# path:
ckpt: # will be overwrite
save_img_path: "./output/samples"
pretrained_model_path: "./ckpts/shared/sd-vae-ft-ema"

# model config: 
model: Latte-L/2-MoE
num_frames: 16
image_size: 256 # choices=[256, 512]
frame_interval: 2
fixed_spatial: False
attention_bias: True
learn_sigma: True
extras: 1 # [1, 2] 1 unconditional generation, 2 class-conditional generation
num_classes:

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed:
sample_method: 'ddpm'
num_sampling_steps: 250
cfg_scale: 1.0
negative_name:

# ddp sample config
per_proc_batch_size: 2
num_fvd_samples: 2048